import type { City, Category, Service, Order, Professional } from '@/lib/types';
import { Wrench, Sparkles, Sprout, PaintRoller, Dumbbell, HeartPulse, HardHat, Car, Shirt, Package, Cctv, Wind, Users, Ruler } from 'lucide-react';

export const CITIES: City[] = [
  { id: '1', name: 'Kukatpally', slug: 'kukatpally' },
  { id: '2', name: 'Madhapur', slug: 'madhapur' },
  { id: '3', name: 'Gachibowli', slug: 'gachibowli' },
  { id: '4', name: 'Ameerpet', slug: 'ameerpet' },
  { id: '5', name: 'Kondapur', slug: 'kondapur' },
  { id: '6', name: 'Secunderabad', slug: 'secunderabad' },
  { id: '7', name: 'Hitech City', slug: 'hitech-city' },
];

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Cleaning & Pest Control',
    slug: 'cleaning',
    icon: Sparkles,
    image: 'category-cleaning',
    description: 'Professional cleaning and pest control for a spotless, safe home.',
  },
  {
    id: '2',
    name: 'AC & Appliance Repair',
    slug: 'repairs',
    icon: Wind,
    image: 'service-ac-repair',
    description: 'Expert repairs for ACs, washing machines, refrigerators, and more.',
  },
  {
    id: '3',
    name: 'Women\'s Salon & Spa',
    slug: 'beauty-wellness',
    icon: HeartPulse,
    image: 'category-beauty',
    description: 'Pamper yourself with our salon and wellness services at home.',
  },
    {
    id: '4',
    name: 'Men\'s Salon',
    slug: 'mens-salon',
    icon: HardHat,
    image: 'category-mens-salon',
    description: 'Grooming services for men, from haircuts to beard trimming.',
  },
  {
    id: '5',
    name: 'Electrician, Plumber & Carpenter',
    slug: 'home-repairs',
    icon: Wrench,
    image: 'category-repairs',
    description: 'All-in-one solutions for your home repair and maintenance needs.',
  },
  {
    id: '6',
    name: 'Painting & Waterproofing',
    slug: 'painting',
    icon: PaintRoller,
    image: 'category-painting',
    description: 'Transform your space with a fresh coat of paint and protect it.',
  },
  {
    id: '7',
    name: 'Gardening & Landscaping',
    slug: 'gardening',
    icon: Sprout,
    image: 'category-gardening',
    description: 'Expert gardening and landscaping services for a beautiful yard.',
  },
  {
    id: '8',
    name: 'Personal Fitness Trainer',
    slug: 'fitness',
    icon: Dumbbell,
    image: 'category-fitness',
    description: 'Personal trainers and yoga instructors at your doorstep.',
  },
  {
    id: '9',
    name: 'Cook / Maid Services',
    slug: 'domestic-help',
    icon: Users,
    image: 'category-domestic-help',
    description: 'Reliable and verified cooks and maids for your daily needs.',
  },
  {
    id: '10',
    name: 'Driver on Demand',
    slug: 'driver',
    icon: Car,
    image: 'category-driver',
    description: 'Hire professional drivers on an hourly or daily basis.',
  },
  {
    id: '11',
    name: 'Laundry & Ironing',
    slug: 'laundry',
    icon: Shirt,
    image: 'category-laundry',
    description: 'Convenient laundry and ironing services with pickup and delivery.',
  },
  {
    id: '12',
    name: 'Packing & Moving',
    slug: 'movers',
    icon: Package,
    image: 'category-movers',
    description: 'Stress-free packing and moving services for your home or office.',
  },
   {
    id: '13',
    name: 'CCTV Installation',
    slug: 'cctv',
    icon: Cctv,
    image: 'category-cctv',
    description: 'Secure your premises with professional CCTV installation.',
  },
];

export const heroServices = [
  { name: "Women's Salon & Spa", icon: HeartPulse, href: "/services/beauty-wellness" },
  { name: "Men's Salon", icon: HardHat, href: "/services/mens-salon" },
  { name: "Cleaning & Pest Control", icon: Sparkles, href: "/services/cleaning" },
  { name: "Electrician, Plumber & Carpenter", icon: Wrench, href: "/services/home-repairs" },
  { name: "Water Purifier", icon: Wrench, href: "/services/repairs" },
  { name: "Painting & Waterproofing", icon: PaintRoller, href: "/services/painting" },
  { name: "AC & Appliance Repair", icon: Wind, href: "/services/repairs" },
  { name: "Home Makeover", icon: Ruler, href: "/services/painting" },
];

export const PROFESSIONALS: Professional[] = [
  { id: '1', name: 'Rajesh Kumar', specialization: 'Electrician', location: 'Kukatpally', rating: 4.8, experience: 10, image: 'prof-1', price: 50 },
  { id: '2', name: 'Suresh Varma', specialization: 'Plumber', location: 'Madhapur', rating: 4.9, experience: 12, image: 'prof-2', price: 55 },
  { id: '3', name: 'Anjali Sharma', specialization: 'Beautician', location: 'Gachibowli', rating: 4.7, experience: 5, image: 'prof-3', price: 60 },
  { id: '4', name: 'Murali Krishna', specialization: 'Carpenter', location: 'Ameerpet', rating: 4.8, experience: 15, image: 'prof-4', price: 45 },
  { id: '5', name: 'Priya Reddy', specialization: 'Cleaner', location: 'Kondapur', rating: 4.9, experience: 4, image: 'prof-5', price: 40 },
  { id: '6', name: 'Vikram Singh', specialization: 'AC Technician', location: 'Secunderabad', rating: 4.9, experience: 8, image: 'prof-6', price: 70 },
  { id: '7', name: 'Ravi Teja', specialization: 'Painter', location: 'Hitech City', rating: 4.6, experience: 7, image: 'prof-7', price: 65 },
  { id: '8', name: 'Sunita Rao', specialization: 'Cook', location: 'Kukatpally', rating: 4.9, experience: 9, image: 'prof-8', price: 35 },
  { id: '9', name: 'Amit Patel', specialization: 'Driver', location: 'Madhapur', rating: 4.7, experience: 11, image: 'prof-9', price: 80 },
  { id: '10', name: 'Kavita Nair', specialization: 'Yoga Instructor', location: 'Gachibowli', rating: 5.0, experience: 6, image: 'prof-10', price: 90 },
  { id: '11', name: 'Balu G.', specialization: 'Mechanic', location: 'Ameerpet', rating: 4.5, experience: 14, image: 'prof-11', price: 75 },
  { id: '12', name: 'Naveen Reddy', specialization: 'Packer & Mover', location: 'Kondapur', rating: 4.8, experience: 5, image: 'prof-12', price: 100 },
  { id: '13', name: 'Santosh Gupta', specialization: 'CCTV Installer', location: 'Secunderabad', rating: 4.9, experience: 7, image: 'prof-13', price: 85 },
  { id: '14', name: 'Deepika Iyer', specialization: 'Maid', location: 'Hitech City', rating: 4.6, experience: 3, image: 'prof-14', price: 30 },
  { id: '15', name: 'Arjun Das', specialization: 'Gardener', location: 'Kukatpally', rating: 4.7, experience: 8, image: 'prof-15', price: 50 },
  { id: '16', name: 'Imran Khan', specialization: 'Electrician', location: 'Madhapur', rating: 4.9, experience: 9, image: 'prof-16', price: 52 },
  { id: '17', name: 'Pooja Hegde', specialization: 'Beautician', location: 'Gachibowli', rating: 4.8, experience: 7, image: 'prof-17', price: 65 },
  { id: '18', name: 'Ramesh Babu', specialization: 'Plumber', location: 'Ameerpet', rating: 4.7, experience: 18, image: 'prof-18', price: 58 },
  { id: '19', 'name': 'Aditya V.', specialization: 'AC Technician', location: 'Kondapur', rating: 5.0, experience: 10, image: 'prof-19', price: 72 },
  { id: '20', name: 'Lakshmi Manchu', specialization: 'Cleaner', location: 'Secunderabad', rating: 4.8, experience: 6, image: 'prof-20', price: 42 },
  { id: '21', name: 'Karthik Aryan', specialization: 'Carpenter', location: 'Hitech City', rating: 4.6, experience: 9, image: 'prof-21', price: 48 },
  { id: '22', name: 'John Doe', specialization: 'Painter', location: 'Kukatpally', rating: 4.8, experience: 5, image: 'prof-22', price: 68 },
  { id: '23', name: 'Jane Doe', specialization: 'Cook', location: 'Madhapur', rating: 4.9, experience: 4, image: 'prof-23', price: 38 },
  { id: '24', name: 'Anil Kapoor', specialization: 'Driver', location: 'Gachibowli', rating: 4.7, experience: 20, image: 'prof-24', price: 82 },
  { id: '25', name: 'Shilpa Shetty', specialization: 'Yoga Instructor', location: 'Ameerpet', rating: 5.0, experience: 15, image: 'prof-25', price: 95 }
];

export const SERVICES: Service[] = [
  {
    id: '1',
    name: 'Deep Home Cleaning',
    slug: 'deep-home-cleaning',
    category: 'cleaning',
    location: 'Madhapur',
    image: 'service-deep-cleaning',
    price: 120,
    rating: 4.8,
    reviewsCount: 250,
    shortDescription: 'A thorough cleaning for a sparkling home.',
    description: 'Our most popular service. We clean every nook and cranny, ensuring your home is left spotless. Ideal for a seasonal clean or before a special occasion.',
    included: ['Dusting and wiping all surfaces', 'Vacuuming and mopping floors', 'Kitchen and bathroom deep clean', 'Window cleaning (interior)'],
    pricingTiers: [
      { name: 'Standard', price: 120, features: ['2-bedroom home', '3-4 hours'] },
      { name: 'Premium', price: 180, features: ['3-4 bedroom home', '4-6 hours', 'Oven cleaning'] },
    ],
    reviews: [
      { id: 'r1', author: 'Jane D.', rating: 5, comment: 'Absolutely amazing! My apartment has never been this clean.', date: '2023-05-10', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d' },
      { id: 'r2', author: 'Mike P.', rating: 4, comment: 'Great service, very professional team. Missed a small spot but overall excellent.', date: '2023-05-08', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026705d' },
    ],
    faqs: [
      { question: 'Do I need to provide cleaning supplies?', answer: 'No, our team comes fully equipped with all necessary supplies and equipment.' },
      { question: 'How long does it take?', answer: 'A standard deep clean for a 2-bedroom home typically takes 3-4 hours.' },
    ],
  },
  {
    id: '2',
    name: 'AC Repair & Service',
    slug: 'ac-repair-service',
    category: 'repairs',
    location: 'Gachibowli',
    image: 'service-ac-repair',
    price: 80,
    rating: 4.9,
    reviewsCount: 412,
    shortDescription: 'Fast and reliable AC repair services.',
    description: 'Don\'t sweat it! Our certified technicians can diagnose and fix any issue with your air conditioning unit, ensuring you stay cool and comfortable.',
    included: ['Diagnosis of issue', 'Filter cleaning', 'Coolant level check', 'Performance test'],
    pricingTiers: [
      { name: 'Inspection', price: 40, features: ['Full diagnosis and quote'] },
      { name: 'Standard Service', price: 80, features: ['Includes cleaning and basic tune-up'] },
      { name: 'Repair', price: 150, features: ['Standard service + replacement of minor parts'] },
    ],
    reviews: [
      { id: 'r3', author: 'Carlos R.', rating: 5, comment: 'Fixed my AC in under an hour. Super impressive!', date: '2023-06-20', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026706d' },
    ],
    faqs: [
      { question: 'Is there a warranty on repairs?', answer: 'Yes, we offer a 90-day warranty on all parts and labor.' },
    ],
  },
  {
    id: '3',
    name: 'Salon at Home',
    slug: 'salon-at-home',
    category: 'beauty-wellness',
    location: 'Kukatpally',
    image: 'service-salon',
    price: 60,
    rating: 4.7,
    reviewsCount: 180,
    shortDescription: 'Get pampered in the comfort of your home.',
    description: 'Why go to the salon when the salon can come to you? Our professional beauticians offer a range of services from manicures to facials.',
    included: ['Manicure & Pedicure', 'Facial', 'Haircut & Styling'],
    pricingTiers: [
      { name: 'Classic Manicure', price: 60, features: ['Nail shaping, cuticle care, polish'] },
      { name: 'Glow Facial', price: 90, features: ['Deep cleansing, exfoliation, mask'] },
      { name: 'Haircut & Blowdry', price: 100, features: ['Consultation, wash, cut, style'] },
    ],
    reviews: [
      { id: 'r4', author: 'Priya K.', rating: 5, comment: 'So convenient and the results were fantastic. My new favorite way to relax.', date: '2023-06-15', avatar: 'https://i.pravatar.cc/150?u=a042581f4e29026707d' },
    ],
    faqs: [
      { question: 'Are your products safe?', answer: 'We use only high-quality, hypoallergenic products from trusted brands.' },
    ],
  },
  {
    id: '4',
    name: 'Interior Wall Painting',
    slug: 'interior-wall-painting',
    category: 'painting',
    location: 'Secunderabad',
    image: 'service-painting',
    price: 300,
    rating: 4.8,
    reviewsCount: 95,
    shortDescription: 'A fresh coat of paint to transform your room.',
    description: 'Revitalize your living space with our professional interior painting services. We handle everything from prep to cleanup, leaving you with a flawless finish.',
    included: ['Surface preparation', 'Two coats of premium paint', 'Furniture covering', 'Post-painting cleanup'],
    pricingTiers: [
      { name: 'Single Room (up to 12x12 ft)', price: 300, features: ['Walls only'] },
      { name: 'Large Room (up to 20x20 ft)', price: 500, features: ['Walls only'] },
      { name: 'Full Apartment (2-bed)', price: 1200, features: ['Includes ceilings and trim'] },
    ],
    reviews: [],
    faqs: [],
  },
  {
    id: '5',
    name: 'Leaky Faucet Repair',
    slug: 'leaky-faucet-repair',
    category: 'home-repairs',
    location: 'Ameerpet',
    image: 'service-plumbing',
    price: 75,
    rating: 4.9,
    reviewsCount: 320,
    shortDescription: 'Stop the drip, save water and money.',
    description: 'A dripping faucet can be annoying and wasteful. Our expert plumbers will fix it quickly and efficiently.',
    included: ['Diagnosis', 'Washer/O-ring replacement', 'Leak test'],
    pricingTiers: [{ name: 'Standard Repair', price: 75, features: ['Fix for one faucet'] }],
    reviews: [],
    faqs: [],
  },
  {
    id: '6',
    name: 'Personal Yoga Session',
    slug: 'personal-yoga-session',
    category: 'fitness',
    location: 'Hitech City',
    image: 'service-yoga',
    price: 90,
    rating: 5.0,
    reviewsCount: 150,
    shortDescription: 'Personalized yoga instruction at home.',
    description: 'Achieve your wellness goals with a one-on-one yoga session tailored to your skill level and needs, from beginner to advanced.',
    included: ['1-hour session', 'Personalized routine', 'Mindfulness practice'],
    pricingTiers: [
        { name: 'Single Session', price: 90, features: ['60-minute session'] },
        { name: '5-Session Pack', price: 400, features: ['5 x 60-minute sessions'] }
    ],
    reviews: [],
    faqs: [],
  },
];

export const USER_ORDERS: Order[] = [
  { id: '1', serviceName: 'Deep Home Cleaning', serviceImage: 'service-deep-cleaning', date: '2023-05-15', amount: 120, status: 'Completed' },
  { id: '2', serviceName: 'AC Repair & Service', serviceImage: 'service-ac-repair', date: '2023-06-21', amount: 80, status: 'Completed' },
  { id: '3', serviceName: 'Interior Wall Painting', serviceImage: 'service-painting', date: '2023-07-05', amount: 300, status: 'Pending' },
];
