
import type { City, Category, Service, Professional } from '@/lib/types';

export const CITIES: City[] = [
  { id: '1', name: 'Kukatpally', slug: 'kukatpally' },
  { id: '2', name: 'Madhapur', slug: 'madhapur' },
  { id: '3', name: 'Gachibowli', slug: 'gachibowli' },
  { id: '4', name: 'Ameerpet', slug: 'ameerpet' },
  { id: '5', name: 'Kondapur', slug: 'kondapur' },
  { id: '6', name: 'Secunderabad', slug: 'secunderabad' },
  { id: '7', name: 'Hitech City', slug: 'hitech-city' },
];

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Home Maintenance',
    slug: 'home-maintenance',
    image: 'category-repairs',
    description: 'Essential services to keep your home in top shape.',
  },
  {
    id: '2',
    name: 'Outdoor Services',
    slug: 'outdoor-services',
    image: 'category-gardening',
    description: 'Services for your yard, garden, and property exterior.',
  },
  {
    id: '3',
    name: 'Cleaning',
    slug: 'cleaning',
    image: 'category-cleaning',
    description: 'Professional cleaning for a spotless home.',
  },
  {
    id: '4',
    name: 'Painting',
    slug: 'painting',
    image: 'category-painting',
    description: 'Transform your space with a fresh coat of paint.',
  },
];

export const PROFESSIONALS: Professional[] = [
  { id: '1', name: 'Rajesh Kumar', specialization: 'Electrician', location: 'Kukatpally', rating: 4.8, experience: 10, image: 'prof-1', price: 50, featured: true, verified: true },
  { id: '2', name: 'Suresh Varma', specialization: 'Plumber', location: 'Madhapur', rating: 4.9, experience: 12, image: 'prof-2', price: 55, featured: false, verified: true },
  { id: '3', name: 'Vikram Singh', specialization: 'Painter', location: 'Secunderabad', rating: 4.9, experience: 8, image: 'prof-6', price: 70, featured: true, verified: true },
  { id: '4', name: 'Arjun Das', specialization: 'Trees Work', location: 'Kukatpally', rating: 4.7, experience: 8, image: 'prof-15', price: 50, featured: false, verified: true },
  { id: '5', name: 'Ravi Teja', specialization: 'Painter', location: 'Hitech City', rating: 4.6, experience: 7, image: 'prof-7', price: 65, featured: false, verified: false },
  { id: '6', name: 'Imran Khan', specialization: 'Electrician', location: 'Madhapur', rating: 4.9, experience: 9, image: 'prof-16', price: 52, featured: false, verified: true },
  { id: '7', name: 'Ramesh Babu', specialization: 'Plumber', location: 'Ameerpet', rating: 4.7, experience: 18, image: 'prof-18', price: 58, featured: true, verified: true },
  { id: '8', name: 'Mani Kandan', specialization: 'Coconut Climber', location: 'Gachibowli', rating: 4.9, experience: 15, image: 'prof-coconut', price: 40, featured: true, verified: true },
  { id: '9', name: 'Siva Kumar', specialization: 'Courtyard Cleaning', location: 'Kondapur', rating: 4.8, experience: 5, image: 'prof-cleaning', price: 45, featured: false, verified: true },
  { id: '10', name: 'Bala Murugan', specialization: 'Scrap Collection', location: 'Secunderabad', rating: 4.7, experience: 6, image: 'prof-scrap', price: 30, featured: false, verified: false },
];

export const SERVICES: Service[] = [
  {
    id: '1',
    name: 'Courtyard Cleaning',
    slug: 'courtyard-cleaning',
    category: 'home-maintenance',
    location: 'Kukatpally',
    image: 'service-courtyard-cleaning',
    price: 90,
    rating: 4.7,
    reviewsCount: 150,
    shortDescription: 'Comprehensive cleaning for your courtyard and outdoor areas.',
    description: 'Our team will handle sweeping, debris removal, and washing to ensure your courtyard is spotless and presentable. Perfect for routine maintenance or after events.',
    included: ['Sweeping and leaf blowing', 'Debris and trash removal', 'Pressure washing of paved areas', 'Weed removal from cracks'],
    pricingTiers: [
      { name: 'Standard', price: 90, features: ['Up to 500 sq ft', '2-3 hours'] },
      { name: 'Large', price: 150, features: ['Up to 1000 sq ft', '3-4 hours'] },
    ],
    reviews: [],
    faqs: [
      { question: 'Do you bring your own equipment?', answer: 'Yes, our team arrives with all necessary equipment, including pressure washers and cleaning agents.' },
      { question: 'How often should I get this service?', answer: 'We recommend monthly cleaning for best results, but we offer one-time services as well.' },
    ],
    tags: ['Popular'],
  },
  {
    id: '2',
    name: 'Coconut Climber',
    slug: 'coconut-climber',
    category: 'outdoor-services',
    location: 'Gachibowli',
    image: 'service-coconut-climbing',
    price: 50,
    rating: 4.9,
    reviewsCount: 210,
    shortDescription: 'Professional and safe coconut harvesting from your trees.',
    description: 'Our experienced coconut climbers use safe and efficient techniques to harvest coconuts from your trees without causing any damage to the tree or your property.',
    included: ['Harvesting from up to 3 trees', 'Safe lowering of coconuts', 'Basic cleanup of fallen fronds'],
    pricingTiers: [
      { name: 'Per Tree', price: 50, features: ['Price is per tree, minimum of 2 trees'] },
      { name: 'Bulk (5+ trees)', price: 40, features: ['Discounted rate for 5 or more trees'] },
    ],
    reviews: [],
    faqs: [
      { question: 'Is the service safe?', answer: 'Absolutely. Our climbers are trained and use safety harnesses and proper equipment to ensure a safe operation.' },
    ],
    tags: ['Instant', 'Popular'],
  },
  {
    id: '3',
    name: 'Plumber',
    slug: 'plumber-services',
    category: 'home-maintenance',
    location: 'Madhapur',
    image: 'service-plumbing',
    price: 75,
    rating: 4.8,
    reviewsCount: 320,
    shortDescription: 'Reliable plumbing solutions for leaks, clogs, and installations.',
    description: 'From leaky faucets to major pipe installations, our certified plumbers provide fast and effective solutions to all your plumbing needs.',
    included: ['Issue diagnosis', 'Leak repair', 'Drain cleaning', 'Fixture installation'],
    pricingTiers: [
      { name: 'Minor Repair (e.g., faucet)', price: 75, features: ['Up to 1 hour of labor'] },
      { name: 'Major Repair (e.g., pipe)', price: 150, features: ['Includes parts and labor'] },
    ],
    reviews: [],
    faqs: [
       { question: 'Do you offer emergency services?', answer: 'Yes, we offer 24/7 emergency plumbing services at an additional charge.' },
    ],
    tags: ['Instant'],
  },
  {
    id: '4',
    name: 'Electrician',
    slug: 'electrician-services',
    category: 'home-maintenance',
    location: 'Ameerpet',
    image: 'service-electrician',
    price: 80,
    rating: 4.8,
    reviewsCount: 290,
    shortDescription: 'Safe and certified electrical services for your home.',
    description: 'Our licensed electricians handle everything from outlet installation and light fixture changes to complete home wiring and panel upgrades.',
    included: ['Safety inspection', 'Wiring and installations', 'Fixture repair/replacement', 'Troubleshooting'],
     pricingTiers: [
      { name: 'Basic Task (e.g., outlet)', price: 80, features: ['Up to 1 hour of labor'] },
      { name: 'Complex Task (e.g., wiring)', price: 160, features: ['Materials and labor included'] },
    ],
    reviews: [],
    faqs: [],
    tags: ['Popular'],
  },
  {
    id: '5',
    name: 'Scrap Collection',
    slug: 'scrap-collection',
    category: 'home-maintenance',
    location: 'Secunderabad',
    image: 'service-scrap-collection',
    price: 30,
    rating: 4.6,
    reviewsCount: 110,
    shortDescription: 'Hassle-free collection of household and industrial scrap.',
    description: 'Clear out your clutter. We collect all types of scrap materials including metal, plastic, and old appliances right from your doorstep.',
    included: ['On-site weighing', 'Instant payment (if applicable)', 'Removal of all specified scrap'],
    pricingTiers: [
      { name: 'Collection Fee', price: 30, features: ['Base fee for visit', 'Value of scrap may offset fee'] },
    ],
    reviews: [],
    faqs: [],
  },
  {
    id: '6',
    name: 'Painter',
    slug: 'painter-services',
    category: 'home-maintenance',
    location: 'Hitech City',
    image: 'service-painting',
    price: 250,
    rating: 4.7,
    reviewsCount: 130,
    shortDescription: 'Professional interior and exterior painting services.',
    description: 'Transform your home with a fresh coat of paint. Our team ensures a smooth, even finish with meticulous attention to detail, from prep to cleanup.',
    included: ['Surface preparation', 'Two coats of premium paint', 'Furniture covering', 'Post-painting cleanup'],
    pricingTiers: [
      { name: 'Single Room (up to 12x12 ft)', price: 250, features: ['Walls only'] },
      { name: 'Exterior Wall (per 100 sq ft)', price: 350, features: ['Includes weather-proof paint'] },
    ],
    reviews: [],
    faqs: [],
    tags: ['Popular'],
  },
  {
    id: '7',
    name: 'Trees Work',
    slug: 'trees-work',
    category: 'outdoor-services',
    location: 'Kondapur',
    image: 'service-trees-work',
    price: 120,
    rating: 4.8,
    reviewsCount: 95,
    shortDescription: 'Expert tree trimming, pruning, and removal services.',
    description: 'Maintain the health and appearance of your trees with our professional arborists. We offer safe and effective tree trimming, pruning, and removal services.',
    included: ['Tree health assessment', 'Pruning or trimming', 'Debris cleanup and removal'],
    pricingTiers: [
      { name: 'Tree Trimming', price: 120, features: ['For one medium-sized tree'] },
      { name: 'Tree Removal', price: 400, features: ['Includes stump grinding consultation'] },
    ],
    reviews: [],
    faqs: [],
  },
];
